using Avalonia;

namespace CubeShelf.Desktop;

internal static class UiLocalization
{
    private static readonly IReadOnlyDictionary<string, string> French = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["AppLibrary"] = "Bibliothèque",
        ["AppFavorites"] = "Favoris",
        ["AppMods"] = "Mods du jeu",
        ["AppDownloads"] = "Téléchargements",
        ["AppFriends"] = "Amis",
        ["FriendsEyebrow"] = "AMIS",
        ["FriendsTitle"] = "Tes amis",
        ["FriendsEmpty"] = "Personne pour l'instant. Partage ton code ami depuis les Paramètres, puis ajoute celui qu'on te donne.",
        ["FriendsRefresh"] = "Actualiser",
        ["AddFriend"] = "Ajouter un ami",
        ["FriendRemove"] = "Retirer",
        ["FriendCopyCode"] = "Copier son code",
        ["MyProfile"] = "Ton profil",
        ["MyProfileHelp"] = "Ce que tes amis voient de toi à côté de ton nom. Rien ici n'est obligatoire, et tout part dans le même document chiffré que ta présence.",
        ["ProfileStatus"] = "Statut",
        ["ProfileStatusHint"] = "Ce que tu as envie de dire (140 caractères)",
        ["ProfileAvatar"] = "Avatar",
        ["ProfileAvatarChoose"] = "Choisir une image…",
        ["ProfileAvatarClear"] = "Retirer",
        ["ProfileAvatarHelp"] = "Redimensionné en 96×96 avant d'être publié : ce document est réécrit à chaque battement, une grande image en ferait un flux constant.",
        ["ProfilePinned"] = "Jeu mis en avant",
        ["ProfilePinnedNone"] = "Aucun",
        ["ShareProfile"] = "Mon profil (statut, avatar, jeu mis en avant)",
        ["FriendBlock"] = "Bloquer",
        ["FriendUnblock"] = "Débloquer",
        ["FriendsBlockedSection"] = "Bloqués",
        ["PlayTogether"] = "JOUER ENSEMBLE",
        ["PlayTogetherHelp"] = "CubeShelf ne crée pas le salon : le compagnon en ligne du runtime le fait. Ouvre-le, crée ton salon, puis colle ici le code qu'il te donne. CubeShelf le transporte chiffré jusqu'à tes amis et le fait expirer tout seul.",
        ["OpenCompanion"] = "Ouvrir le compagnon en ligne",
        ["InviteCodeHint"] = "Code d'invitation donné par le compagnon",
        ["PublishInvite"] = "Inviter mes amis",
        ["HostLobbyInvite"] = "Créer un salon et inviter mes amis",
        ["InviteManual"] = "Déjà un salon ouvert ? Colle son code ici.",
        ["CancelInvite"] = "Retirer l'invitation",
        ["FriendJoin"] = "Rejoindre",
        ["Presence"] = "Amis et présence",
        ["PresenceHelp"] = "CubeShelf publie ta présence dans un dossier que tu synchronises déjà (Nextcloud, Dropbox…) et lit celle de tes amis depuis le lien qu'ils t'ont donné. Aucun serveur, aucun compte, aucun mot de passe enregistré.",
        ["PresenceDisplayName"] = "Nom affiché",
        ["PresenceDisplayNameHint"] = "Le nom que tes amis verront",
        ["PresenceDisplayNameHelp"] = "Laissé vide par défaut : ton nom de compte Windows ne sera jamais publié sans que tu le tapes.",
        ["PresenceFolder"] = "Dossier de publication",
        ["PresenceBrowse"] = "Parcourir…",
        ["PresenceUrl"] = "Adresse publique de ce fichier",
        ["PresenceUrlHelp"] = "Le lien de partage doit servir le fichier lui-même : un partage Nextcloud demande /download à la fin. Change cette adresse et tous les codes amis déjà distribués cessent de fonctionner.",
        ["PresenceTest"] = "Tester l'adresse",
        ["PresencePublish"] = "Publier ma présence",
        ["PresenceSettings"] = "Réglages",
        ["MyFriendCode"] = "Ton code ami",
        ["MyFriendCodeHint"] = "Disponible après un test réussi",
        ["Copy"] = "Copier",
        ["WhatYouShare"] = "Ce que tu partages",
        ["ShareLibrary"] = "Ma bibliothèque",
        ["SharePlayTime"] = "Mon temps de jeu",
        ["ShareCurrentGame"] = "Le jeu auquel je joue",
        ["ShareMods"] = "Mes mods installés",
        ["AppSettings"] = "Paramètres",
        ["LibraryEyebrow"] = "BIBLIOTHÈQUE",
        ["LibraryTitle"] = "Tes jeux GameCube",
        ["AddGame"] = "+ Ajouter un jeu",
        ["LibrarySubtitle"] = "Les mises à jour GitHub sont vérifiées automatiquement. Sélectionne un jeu pour continuer.",
        ["SearchGame"] = "Rechercher un jeu…",
        ["SortName"] = "Nom A-Z",
        ["SortRecent"] = "Récemment joué",
        ["SortPlaytime"] = "Temps de jeu",
        ["Queue"] = "FILE D'ATTENTE",
        ["QueueEmpty"] = "Aucune opération",
        ["BackLibrary"] = "← Bibliothèque",
        ["FlipCase"] = "↻ Retourner",
        ["SelectedGame"] = "NINTENDO GAMECUBE • JEU SÉLECTIONNÉ",
        ["Mods"] = "🧩 Mods",
        ["RefreshGameBanana"] = "↻ Actualiser GameBanana",
        ["DownloadsEyebrow"] = "TÉLÉCHARGEMENTS",
        ["DownloadsTitle"] = "File d'attente",
        ["DownloadsSubtitle"] = "Jeux, mods et mises à jour sont traités dans l'ordre avec progression et liste des changements.",
        ["SettingsEyebrow"] = "PARAMÈTRES",
        ["SettingsTitle"] = "Personnaliser CubeShelf",
        ["SettingsSubtitle"] = "Langue, apparence, mises à jour et comportement de la bibliothèque.",
        ["Language"] = "Langue",
        ["LanguageHelp"] = "Change immédiatement la langue de l'interface.",
        ["Appearance"] = "Apparence",
        ["AppearanceHelp"] = "Le changement de thème est animé et mémorisé.",
        ["UpdateSettings"] = "Mises à jour",
        ["WindowLayout"] = "Fenêtre",
        ["WindowLayoutHelp"] = "Adapte CubeShelf à la taille et au DPI de l’écran actuel.",
        ["AutoFitWindow"] = "Adapter automatiquement",
        ["FitWindowNow"] = "Adapter maintenant",
        ["Storage"] = "Stockage",
        ["Diagnostics"] = "Diagnostic",
        ["OpenDiagnostics"] = "Ouvrir le diagnostic",
        ["FirstRunAssistant"] = "Assistant de démarrage",
        ["RunAssistant"] = "Relancer l’assistant",
        ["ResetSettings"] = "Réinitialiser les paramètres",
        ["CheckLauncherUpdate"] = "Vérifier les mises à jour de CubeShelf",
        ["DolphinToolTitle"] = "DolphinTool / RVZ",
        ["DolphinDetect"] = "Détecter",
        ["DolphinInstall"] = "Installer automatiquement",
        ["OpenTools"] = "Ouvrir les outils",
        ["OpenDataFolder"] = "Ouvrir les données",
        ["Refresh"] = "Actualiser",
        ["CleanCache"] = "Nettoyer le cache",
        ["ClearFinished"] = "Effacer les opérations terminées",
        ["CancelDownload"] = "Annuler",
        ["ResumeDownload"] = "Reprendre",
        ["RetryDownload"] = "Réessayer",
        ["RemoveQueue"] = "Retirer",
        ["FavoritesTitle"] = "Favoris",
        ["NoLibraryMatch"] = "Aucun jeu ne correspond à ce filtre.",
        ["BackGame"] = "← Retour au jeu",
        ["GameUpdates"] = "GITHUB / MISES À JOUR",
        ["InstalledMods"] = "MODS INSTALLÉS",
        ["NoModsInstalled"] = "Aucun mod installé. Ouvre le gestionnaire pour en ajouter depuis GameBanana.",
        ["ManageMods"] = "Gérer les mods",
        ["Check"] = "Vérifier",
        ["DownloadSource"] = "Télécharger la source",
        ["DeleteSource"] = "Supprimer la source",
        ["InstallPartyBoard"] = "Installer PartyBoard",
        ["ChooseDisc"] = "Choisir ISO / GCM / RVZ",
        ["Clear"] = "Effacer",
        ["PrepareGameData"] = "Préparer les données",
        ["ManualExecutable"] = "Choisir manuellement",
        ["Repair"] = "Réparer",
        ["Uninstall"] = "Désinstaller",
        ["Play"] = "▶ Jouer",
        ["Priority"] = "Priorité",
        ["Apply"] = "Appliquer",
        ["Install"] = "Installer",
        ["Enable"] = "Activer",
        ["Delete"] = "Supprimer",
        ["ViewImage"] = "Voir l’image",
        ["GameBanana"] = "GameBanana",
        ["SelectMod"] = "Sélectionne un mod",
        ["OpenData"] = "Ouvrir les données",
        ["StartupAssistantHelp"] = "Relance le guide langue, thème, stockage et configuration du jeu.",
        ["DiagnosticsHelp"] = "Vérifie la plateforme, le runtime, l’ISO/RVZ, les données et les mods.",
        ["DolphinHelp"] = "CubeShelf utilise DolphinTool uniquement pour convertir les images RVZ avant extraction.",
        ["UpdateAtStartup"] = "Vérifier les mises à jour des jeux au démarrage",
        ["UpdatePopup"] = "Afficher une notification de mise à jour",
        ["RefreshModsOnOpen"] = "Actualiser GameBanana à l’ouverture des mods",
        ["ThemeDark"] = "Sombre",
        ["ThemeLight"] = "Clair",
        ["BrandSubtitle"] = "Bibliothèque GameCube",
        ["LibraryCountLabel"] = "BIBLIOTHÈQUE",
        ["GameUpdateUnknown"] = "○ Mise à jour non vérifiée",
        ["GameDiscLabel"] = "IMAGE DU JEU",
        ["NoDisc"] = "Aucune image sélectionnée",
        ["PartyBoardLabel"] = "PARTYBOARD",
        ["NoRuntime"] = "PartyBoard non configuré",
        ["FavoriteAdd"] = "☆ Ajouter aux favoris",
        ["FavoriteRemove"] = "★ Retirer des favoris",
        ["ModsEyebrow"] = "MODS",
        ["OfflineTitle"] = "Mode local",
        ["OfflineRetry"] = "Réessayer",
        ["Shortcuts"] = "Raccourcis clavier",
        ["ShortcutsHelp"] = "CubeShelf reste entièrement utilisable sans souris.",
        ["Retry"] = "Réessayer",
        ["Close"] = "Fermer",
        ["Cancel"] = "Annuler",
        ["Later"] = "Plus tard",
        ["Download"] = "Télécharger",
        ["UpdateNow"] = "Mettre à jour maintenant",
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["AppLibrary"] = "Library",
        ["AppFavorites"] = "Favorites",
        ["AppMods"] = "Game Mods",
        ["AppDownloads"] = "Downloads",
        ["AppFriends"] = "Friends",
        ["FriendsEyebrow"] = "FRIENDS",
        ["FriendsTitle"] = "Your friends",
        ["FriendsEmpty"] = "Nobody yet. Share your friend code from Settings, then add the one you are given.",
        ["FriendsRefresh"] = "Refresh",
        ["AddFriend"] = "Add a friend",
        ["FriendRemove"] = "Remove",
        ["FriendCopyCode"] = "Copy their code",
        ["MyProfile"] = "Your profile",
        ["MyProfileHelp"] = "What your friends see beside your name. None of it is required, and all of it travels in the same encrypted document as your presence.",
        ["ProfileStatus"] = "Status",
        ["ProfileStatusHint"] = "Whatever you feel like saying (140 characters)",
        ["ProfileAvatar"] = "Avatar",
        ["ProfileAvatarChoose"] = "Choose an image…",
        ["ProfileAvatarClear"] = "Remove",
        ["ProfileAvatarHelp"] = "Resized to 96×96 before it is published: this document is rewritten on every heartbeat, and a large image would make it a constant stream.",
        ["ProfilePinned"] = "Featured game",
        ["ProfilePinnedNone"] = "None",
        ["ShareProfile"] = "My profile (status, avatar, featured game)",
        ["FriendBlock"] = "Block",
        ["FriendUnblock"] = "Unblock",
        ["FriendsBlockedSection"] = "Blocked",
        ["PlayTogether"] = "PLAY TOGETHER",
        ["PlayTogetherHelp"] = "CubeShelf does not create the lobby: the runtime's online companion does. Open it, create your lobby, then paste the code it gives you here. CubeShelf carries it encrypted to your friends and expires it on its own.",
        ["OpenCompanion"] = "Open the online companion",
        ["InviteCodeHint"] = "Invitation code from the companion",
        ["PublishInvite"] = "Invite my friends",
        ["HostLobbyInvite"] = "Create a lobby and invite my friends",
        ["InviteManual"] = "Already have a lobby open? Paste its code here.",
        ["CancelInvite"] = "Withdraw the invitation",
        ["FriendJoin"] = "Join",
        ["Presence"] = "Friends and presence",
        ["PresenceHelp"] = "CubeShelf publishes your presence into a folder you already synchronise (Nextcloud, Dropbox…) and reads your friends' from the link they gave you. No server, no account, no stored password.",
        ["PresenceDisplayName"] = "Display name",
        ["PresenceDisplayNameHint"] = "The name your friends will see",
        ["PresenceDisplayNameHelp"] = "Empty by default: your Windows account name is never published unless you type it.",
        ["PresenceFolder"] = "Publishing folder",
        ["PresenceBrowse"] = "Browse…",
        ["PresenceUrl"] = "Public address of that file",
        ["PresenceUrlHelp"] = "The share link must serve the file itself: a Nextcloud share needs /download at the end. Change this address and every friend code already handed out stops working.",
        ["PresenceTest"] = "Test the address",
        ["PresencePublish"] = "Publish my presence",
        ["PresenceSettings"] = "Settings",
        ["MyFriendCode"] = "Your friend code",
        ["MyFriendCodeHint"] = "Available after a successful test",
        ["Copy"] = "Copy",
        ["WhatYouShare"] = "What you share",
        ["ShareLibrary"] = "My library",
        ["SharePlayTime"] = "My play time",
        ["ShareCurrentGame"] = "The game I am playing",
        ["ShareMods"] = "My installed mods",
        ["AppSettings"] = "Settings",
        ["LibraryEyebrow"] = "LIBRARY",
        ["LibraryTitle"] = "Your GameCube games",
        ["AddGame"] = "+ Add a game",
        ["LibrarySubtitle"] = "GitHub updates are checked automatically. Select a game to continue.",
        ["SearchGame"] = "Search games…",
        ["SortName"] = "Name A-Z",
        ["SortRecent"] = "Recently played",
        ["SortPlaytime"] = "Play time",
        ["Queue"] = "DOWNLOAD QUEUE",
        ["QueueEmpty"] = "No operation",
        ["BackLibrary"] = "← Library",
        ["FlipCase"] = "↻ Flip",
        ["SelectedGame"] = "NINTENDO GAMECUBE • SELECTED GAME",
        ["Mods"] = "🧩 Mods",
        ["RefreshGameBanana"] = "↻ Refresh GameBanana",
        ["DownloadsEyebrow"] = "DOWNLOADS",
        ["DownloadsTitle"] = "Download queue",
        ["DownloadsSubtitle"] = "Games, mods and updates are processed in order with progress and changelogs.",
        ["SettingsEyebrow"] = "SETTINGS",
        ["SettingsTitle"] = "Customize CubeShelf",
        ["SettingsSubtitle"] = "Language, appearance, updates and library behavior.",
        ["Language"] = "Language",
        ["LanguageHelp"] = "Changes the interface language immediately.",
        ["Appearance"] = "Appearance",
        ["AppearanceHelp"] = "Theme changes are animated and remembered.",
        ["UpdateSettings"] = "Updates",
        ["WindowLayout"] = "Window",
        ["WindowLayoutHelp"] = "Fits CubeShelf to the current screen size and DPI.",
        ["AutoFitWindow"] = "Fit automatically",
        ["FitWindowNow"] = "Fit now",
        ["Storage"] = "Storage",
        ["Diagnostics"] = "Diagnostics",
        ["OpenDiagnostics"] = "Open diagnostics",
        ["FirstRunAssistant"] = "Setup assistant",
        ["RunAssistant"] = "Run assistant again",
        ["ResetSettings"] = "Reset settings",
        ["CheckLauncherUpdate"] = "Check CubeShelf updates",
        ["DolphinToolTitle"] = "DolphinTool / RVZ",
        ["DolphinDetect"] = "Detect",
        ["DolphinInstall"] = "Install automatically",
        ["OpenTools"] = "Open tools",
        ["OpenDataFolder"] = "Open data folder",
        ["Refresh"] = "Refresh",
        ["CleanCache"] = "Clean cache",
        ["ClearFinished"] = "Clear finished operations",
        ["CancelDownload"] = "Cancel",
        ["ResumeDownload"] = "Resume",
        ["RetryDownload"] = "Retry",
        ["RemoveQueue"] = "Remove",
        ["FavoritesTitle"] = "Favorites",
        ["NoLibraryMatch"] = "No game matches this filter.",
        ["BackGame"] = "← Back to game",
        ["GameUpdates"] = "GITHUB / UPDATES",
        ["InstalledMods"] = "INSTALLED MODS",
        ["NoModsInstalled"] = "No mod installed. Open the manager to add one from GameBanana.",
        ["ManageMods"] = "Manage mods",
        ["Check"] = "Check",
        ["DownloadSource"] = "Download source",
        ["DeleteSource"] = "Delete source",
        ["InstallPartyBoard"] = "Install PartyBoard",
        ["ChooseDisc"] = "Choose ISO / GCM / RVZ",
        ["Clear"] = "Clear",
        ["PrepareGameData"] = "Prepare game data",
        ["ManualExecutable"] = "Choose manually",
        ["Repair"] = "Repair",
        ["Uninstall"] = "Uninstall",
        ["Play"] = "▶ Play",
        ["Priority"] = "Priority",
        ["Apply"] = "Apply",
        ["Install"] = "Install",
        ["Enable"] = "Enable",
        ["Delete"] = "Delete",
        ["ViewImage"] = "View image",
        ["GameBanana"] = "GameBanana",
        ["SelectMod"] = "Select a mod",
        ["OpenData"] = "Open data folder",
        ["StartupAssistantHelp"] = "Run the language, theme, storage and game setup guide again.",
        ["DiagnosticsHelp"] = "Checks the platform, runtime, ISO/RVZ, game data and mods.",
        ["DolphinHelp"] = "CubeShelf uses DolphinTool only to convert RVZ images before extraction.",
        ["UpdateAtStartup"] = "Check game updates at startup",
        ["UpdatePopup"] = "Show an update notification",
        ["RefreshModsOnOpen"] = "Refresh GameBanana when opening Mods",
        ["ThemeDark"] = "Dark",
        ["ThemeLight"] = "Light",
        ["BrandSubtitle"] = "GameCube Library",
        ["LibraryCountLabel"] = "LIBRARY",
        ["GameUpdateUnknown"] = "○ Update not checked",
        ["GameDiscLabel"] = "GAME IMAGE",
        ["NoDisc"] = "No image selected",
        ["PartyBoardLabel"] = "PARTYBOARD",
        ["NoRuntime"] = "PartyBoard not configured",
        ["FavoriteAdd"] = "☆ Add to favorites",
        ["FavoriteRemove"] = "★ Remove from favorites",
        ["ModsEyebrow"] = "MODS",
        ["OfflineTitle"] = "Local mode",
        ["OfflineRetry"] = "Retry",
        ["Shortcuts"] = "Keyboard shortcuts",
        ["ShortcutsHelp"] = "CubeShelf remains fully usable without a mouse.",
        ["Retry"] = "Retry",
        ["Close"] = "Close",
        ["Cancel"] = "Cancel",
        ["Later"] = "Later",
        ["Download"] = "Download",
        ["UpdateNow"] = "Update now",
    };

    public static bool IsEnglish(string? language) =>
        string.Equals(language, "en", StringComparison.OrdinalIgnoreCase);

    public static string Get(string? language, string key)
    {
        var dictionary = IsEnglish(language) ? English : French;
        return dictionary.TryGetValue(key, out var text) ? text : key;
    }

    public static void Apply(string? language)
    {
        if (Application.Current is null) return;
        VerifyDictionariesMatch();
        var dictionary = IsEnglish(language) ? English : French;
        foreach (var pair in dictionary)
            Application.Current.Resources[pair.Key] = pair.Value;
    }

    /// <summary>
    /// Apply only writes the selected dictionary, so a key present in one and missing from the
    /// other leaves the previous language's value sitting in the resources -- visible only as a
    /// stray French label in an English window, which nobody notices in review. Cheap to catch
    /// at the one place both dictionaries are known, and only the developer's problem.
    /// </summary>
    [System.Diagnostics.Conditional("DEBUG")]
    private static void VerifyDictionariesMatch()
    {
        if (French.Keys.ToHashSet(StringComparer.Ordinal).SetEquals(English.Keys)) return;

        var missing = French.Keys.Except(English.Keys, StringComparer.Ordinal)
            .Select(key => "EN: " + key)
            .Concat(English.Keys.Except(French.Keys, StringComparer.Ordinal).Select(key => "FR: " + key));
        throw new InvalidOperationException(
            "UiLocalization : les dictionnaires ont divergé — " + string.Join(", ", missing));
    }
}
