using Avalonia;

namespace CubeShelf.Desktop;

internal static class UiLocalization
{
    private static readonly IReadOnlyDictionary<string, string> French = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["AppLibrary"] = "Bibliothèque",
        ["AppFavorites"] = "Favoris",
        ["AppMods"] = "Mods du jeu",
        ["AppDownloads"] = "Téléchargements",
        ["AppSettings"] = "Paramètres",
        ["LibraryEyebrow"] = "BIBLIOTHÈQUE",
        ["LibraryTitle"] = "Tes jeux GameCube",
        ["AddGame"] = "+ Ajouter un jeu",
        ["LibrarySubtitle"] = "Les mises à jour GitHub sont vérifiées automatiquement. Sélectionne un jeu pour continuer.",
        ["SearchGame"] = "Rechercher un jeu…",
        ["SortName"] = "Nom A-Z",
        ["SortRecent"] = "Récemment joué",
        ["SortPlaytime"] = "Temps de jeu",
        ["Queue"] = "FILE D'ATTENTE",
        ["QueueEmpty"] = "Aucune opération",
        ["BackLibrary"] = "← Bibliothèque",
        ["FlipCase"] = "↻ Retourner",
        ["SelectedGame"] = "NINTENDO GAMECUBE • JEU SÉLECTIONNÉ",
        ["Mods"] = "🧩 Mods",
        ["RefreshGameBanana"] = "↻ Actualiser GameBanana",
        ["DownloadsEyebrow"] = "TÉLÉCHARGEMENTS",
        ["DownloadsTitle"] = "File d'attente",
        ["DownloadsSubtitle"] = "Jeux, mods et mises à jour sont traités dans l'ordre avec progression et liste des changements.",
        ["SettingsEyebrow"] = "PARAMÈTRES",
        ["SettingsTitle"] = "Personnaliser CubeShelf",
        ["SettingsSubtitle"] = "Langue, apparence, mises à jour et comportement de la bibliothèque.",
        ["Language"] = "Langue",
        ["LanguageHelp"] = "Change immédiatement la langue de l'interface.",
        ["Appearance"] = "Apparence",
        ["AppearanceHelp"] = "Le changement de thème est animé et mémorisé.",
        ["UpdateSettings"] = "Mises à jour",
        ["WindowLayout"] = "Fenêtre",
        ["WindowLayoutHelp"] = "Adapte CubeShelf à la taille et au DPI de l’écran actuel.",
        ["AutoFitWindow"] = "Adapter automatiquement",
        ["FitWindowNow"] = "Adapter maintenant",
        ["Storage"] = "Stockage",
        ["Diagnostics"] = "Diagnostic",
        ["OpenDiagnostics"] = "Ouvrir le diagnostic",
        ["FirstRunAssistant"] = "Assistant de démarrage",
        ["RunAssistant"] = "Relancer l’assistant",
        ["ResetSettings"] = "Réinitialiser les paramètres",
        ["CheckLauncherUpdate"] = "Vérifier les mises à jour de CubeShelf",
        ["DolphinToolTitle"] = "DolphinTool / RVZ",
        ["DolphinDetect"] = "Détecter",
        ["DolphinInstall"] = "Installer automatiquement",
        ["OpenTools"] = "Ouvrir les outils",
        ["OpenDataFolder"] = "Ouvrir les données",
        ["Refresh"] = "Actualiser",
        ["CleanCache"] = "Nettoyer le cache",
        ["ClearFinished"] = "Effacer les opérations terminées",
        ["CancelDownload"] = "Annuler",
        ["ResumeDownload"] = "Reprendre",
        ["RetryDownload"] = "Réessayer",
        ["RemoveQueue"] = "Retirer",
        ["FavoritesTitle"] = "Favoris",
        ["NoLibraryMatch"] = "Aucun jeu ne correspond à ce filtre.",
        ["BackGame"] = "← Retour au jeu",
        ["GameUpdates"] = "GITHUB / MISES À JOUR",
        ["Check"] = "Vérifier",
        ["DownloadSource"] = "Télécharger la source",
        ["DeleteSource"] = "Supprimer la source",
        ["InstallPartyBoard"] = "Installer PartyBoard",
        ["ChooseDisc"] = "Choisir ISO / GCM / RVZ",
        ["Clear"] = "Effacer",
        ["PrepareGameData"] = "Préparer les données",
        ["ManualExecutable"] = "Choisir manuellement",
        ["Repair"] = "Réparer",
        ["Uninstall"] = "Désinstaller",
        ["Play"] = "▶ Jouer",
        ["Priority"] = "Priorité",
        ["Apply"] = "Appliquer",
        ["Install"] = "Installer",
        ["Enable"] = "Activer",
        ["Delete"] = "Supprimer",
        ["ViewImage"] = "Voir l’image",
        ["GameBanana"] = "GameBanana",
        ["SelectMod"] = "Sélectionne un mod",
        ["OpenData"] = "Ouvrir les données",
        ["StartupAssistantHelp"] = "Relance le guide langue, thème, stockage et configuration du jeu.",
        ["DiagnosticsHelp"] = "Vérifie la plateforme, le runtime, l’ISO/RVZ, les données et les mods.",
        ["DolphinHelp"] = "CubeShelf utilise DolphinTool uniquement pour convertir les images RVZ avant extraction.",
        ["UpdateAtStartup"] = "Vérifier les mises à jour des jeux au démarrage",
        ["UpdatePopup"] = "Afficher une notification de mise à jour",
        ["RefreshModsOnOpen"] = "Actualiser GameBanana à l’ouverture des mods",
        ["ThemeDark"] = "Sombre",
        ["ThemeLight"] = "Clair",
        ["BrandSubtitle"] = "Bibliothèque GameCube",
        ["LibraryCountLabel"] = "BIBLIOTHÈQUE",
        ["GameUpdateUnknown"] = "○ Mise à jour non vérifiée",
        ["GameDiscLabel"] = "IMAGE DU JEU",
        ["NoDisc"] = "Aucune image sélectionnée",
        ["PartyBoardLabel"] = "PARTYBOARD",
        ["NoRuntime"] = "PartyBoard non configuré",
        ["FavoriteAdd"] = "☆ Ajouter aux favoris",
        ["FavoriteRemove"] = "★ Retirer des favoris",
        ["ModsEyebrow"] = "MODS",
        ["OfflineTitle"] = "Mode local",
        ["OfflineRetry"] = "Réessayer",
        ["Shortcuts"] = "Raccourcis clavier",
        ["ShortcutsHelp"] = "CubeShelf reste entièrement utilisable sans souris.",
        ["Retry"] = "Réessayer",
        ["Close"] = "Fermer",
        ["Cancel"] = "Annuler",
        ["Later"] = "Plus tard",
        ["Download"] = "Télécharger",
        ["UpdateNow"] = "Mettre à jour maintenant",
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["AppLibrary"] = "Library",
        ["AppFavorites"] = "Favorites",
        ["AppMods"] = "Game Mods",
        ["AppDownloads"] = "Downloads",
        ["AppSettings"] = "Settings",
        ["LibraryEyebrow"] = "LIBRARY",
        ["LibraryTitle"] = "Your GameCube games",
        ["AddGame"] = "+ Add a game",
        ["LibrarySubtitle"] = "GitHub updates are checked automatically. Select a game to continue.",
        ["SearchGame"] = "Search games…",
        ["SortName"] = "Name A-Z",
        ["SortRecent"] = "Recently played",
        ["SortPlaytime"] = "Play time",
        ["Queue"] = "DOWNLOAD QUEUE",
        ["QueueEmpty"] = "No operation",
        ["BackLibrary"] = "← Library",
        ["FlipCase"] = "↻ Flip",
        ["SelectedGame"] = "NINTENDO GAMECUBE • SELECTED GAME",
        ["Mods"] = "🧩 Mods",
        ["RefreshGameBanana"] = "↻ Refresh GameBanana",
        ["DownloadsEyebrow"] = "DOWNLOADS",
        ["DownloadsTitle"] = "Download queue",
        ["DownloadsSubtitle"] = "Games, mods and updates are processed in order with progress and changelogs.",
        ["SettingsEyebrow"] = "SETTINGS",
        ["SettingsTitle"] = "Customize CubeShelf",
        ["SettingsSubtitle"] = "Language, appearance, updates and library behavior.",
        ["Language"] = "Language",
        ["LanguageHelp"] = "Changes the interface language immediately.",
        ["Appearance"] = "Appearance",
        ["AppearanceHelp"] = "Theme changes are animated and remembered.",
        ["UpdateSettings"] = "Updates",
        ["WindowLayout"] = "Window",
        ["WindowLayoutHelp"] = "Fits CubeShelf to the current screen size and DPI.",
        ["AutoFitWindow"] = "Fit automatically",
        ["FitWindowNow"] = "Fit now",
        ["Storage"] = "Storage",
        ["Diagnostics"] = "Diagnostics",
        ["OpenDiagnostics"] = "Open diagnostics",
        ["FirstRunAssistant"] = "Setup assistant",
        ["RunAssistant"] = "Run assistant again",
        ["ResetSettings"] = "Reset settings",
        ["CheckLauncherUpdate"] = "Check CubeShelf updates",
        ["DolphinToolTitle"] = "DolphinTool / RVZ",
        ["DolphinDetect"] = "Detect",
        ["DolphinInstall"] = "Install automatically",
        ["OpenTools"] = "Open tools",
        ["OpenDataFolder"] = "Open data folder",
        ["Refresh"] = "Refresh",
        ["CleanCache"] = "Clean cache",
        ["ClearFinished"] = "Clear finished operations",
        ["CancelDownload"] = "Cancel",
        ["ResumeDownload"] = "Resume",
        ["RetryDownload"] = "Retry",
        ["RemoveQueue"] = "Remove",
        ["FavoritesTitle"] = "Favorites",
        ["NoLibraryMatch"] = "No game matches this filter.",
        ["BackGame"] = "← Back to game",
        ["GameUpdates"] = "GITHUB / UPDATES",
        ["Check"] = "Check",
        ["DownloadSource"] = "Download source",
        ["DeleteSource"] = "Delete source",
        ["InstallPartyBoard"] = "Install PartyBoard",
        ["ChooseDisc"] = "Choose ISO / GCM / RVZ",
        ["Clear"] = "Clear",
        ["PrepareGameData"] = "Prepare game data",
        ["ManualExecutable"] = "Choose manually",
        ["Repair"] = "Repair",
        ["Uninstall"] = "Uninstall",
        ["Play"] = "▶ Play",
        ["Priority"] = "Priority",
        ["Apply"] = "Apply",
        ["Install"] = "Install",
        ["Enable"] = "Enable",
        ["Delete"] = "Delete",
        ["ViewImage"] = "View image",
        ["GameBanana"] = "GameBanana",
        ["SelectMod"] = "Select a mod",
        ["OpenData"] = "Open data folder",
        ["StartupAssistantHelp"] = "Run the language, theme, storage and game setup guide again.",
        ["DiagnosticsHelp"] = "Checks the platform, runtime, ISO/RVZ, game data and mods.",
        ["DolphinHelp"] = "CubeShelf uses DolphinTool only to convert RVZ images before extraction.",
        ["UpdateAtStartup"] = "Check game updates at startup",
        ["UpdatePopup"] = "Show an update notification",
        ["RefreshModsOnOpen"] = "Refresh GameBanana when opening Mods",
        ["ThemeDark"] = "Dark",
        ["ThemeLight"] = "Light",
        ["BrandSubtitle"] = "GameCube Library",
        ["LibraryCountLabel"] = "LIBRARY",
        ["GameUpdateUnknown"] = "○ Update not checked",
        ["GameDiscLabel"] = "GAME IMAGE",
        ["NoDisc"] = "No image selected",
        ["PartyBoardLabel"] = "PARTYBOARD",
        ["NoRuntime"] = "PartyBoard not configured",
        ["FavoriteAdd"] = "☆ Add to favorites",
        ["FavoriteRemove"] = "★ Remove from favorites",
        ["ModsEyebrow"] = "MODS",
        ["OfflineTitle"] = "Local mode",
        ["OfflineRetry"] = "Retry",
        ["Shortcuts"] = "Keyboard shortcuts",
        ["ShortcutsHelp"] = "CubeShelf remains fully usable without a mouse.",
        ["Retry"] = "Retry",
        ["Close"] = "Close",
        ["Cancel"] = "Cancel",
        ["Later"] = "Later",
        ["Download"] = "Download",
        ["UpdateNow"] = "Update now",
    };

    public static bool IsEnglish(string? language) =>
        string.Equals(language, "en", StringComparison.OrdinalIgnoreCase);

    public static string Get(string? language, string key)
    {
        var dictionary = IsEnglish(language) ? English : French;
        return dictionary.TryGetValue(key, out var text) ? text : key;
    }

    public static void Apply(string? language)
    {
        if (Application.Current is null) return;
        var dictionary = IsEnglish(language) ? English : French;
        foreach (var pair in dictionary)
            Application.Current.Resources[pair.Key] = pair.Value;
    }
}
