<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <AssemblyName>CubeShelf</AssemblyName>
    <Version>0.6.11</Version>
      <ApplicationIcon>Assets\Brand\gamecube_logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.*" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="games.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
<ItemGroup>
    <Resource Include="Assets\Brand\gamecube_logo.png" />
    <Content Include="Assets\Brand\gamecube_logo.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>

